# 05 Build fact_sales

This notebook creates the fact table from the cleaned sales dataset.

Each row in `fact_sales` represents one sales transaction line.

In [2]:
import pandas as pd
import os

In [3]:
input_path = "../data/processed/clean_sales.csv"
output_path = "../data/processed/fact_sales.csv"

In [4]:
df = pd.read_csv(input_path)
df.head()

,ï»¿row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,sales,quantity,discount,profit,order_year,order_month,order_day,order_month_name,order_day_name,date_id
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,261.9600,2,0.00,41.9136,2016,11,8,November,Tuesday,2016-11-08
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,731.9400,3,0.00,219.5820,2016,11,8,November,Tuesday,2016-11-08
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,14.6200,2,0.00,6.8714,2016,6,12,June,Sunday,2016-06-12
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,957.5775,5,0.45,-383.0310,2015,10,11,October,Sunday,2015-10-11
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,22.3680,2,0.20,2.5164,2015,10,11,October,Sunday,2015-10-11

In [5]:
df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce")
df["date_id"] = df["order_date"].dt.date

In [6]:
fact_sales = df[[
    "date_id",
    "customer_id",
    "product_id",
    "quantity",
    "sales",
    "discount",
    "profit"
]].copy()

In [7]:
fact_sales.insert(0, "sales_id", range(1, len(fact_sales) + 1))

In [8]:
fact_sales.head()

,sales_id,date_id,customer_id,product_id,quantity,sales,discount,profit
0,1,2016-11-08,CG-12520,FUR-BO-10001798,2,261.9600,0.00,41.9136
1,2,2016-11-08,CG-12520,FUR-CH-10000454,3,731.9400,0.00,219.5820
2,3,2016-06-12,DV-13045,OFF-LA-10000240,2,14.6200,0.00,6.8714
3,4,2015-10-11,SO-20335,FUR-TA-10000577,5,957.5775,0.45,-383.0310
4,5,2015-10-11,SO-20335,OFF-ST-10000760,2,22.3680,0.20,2.5164

In [9]:
fact_sales.isna().sum()

sales_id       0
date_id        0
customer_id    0
product_id     0
quantity       0
sales          0
discount       0
profit         0
dtype: int64

In [10]:
print("Rows:", len(fact_sales))
print("Unique sales_id:", fact_sales["sales_id"].nunique())
print("Unique customers:", fact_sales["customer_id"].nunique())
print("Unique products:", fact_sales["product_id"].nunique())
print("Date range:", fact_sales["date_id"].min(), "to", fact_sales["date_id"].max())

Rows: 9994
Unique sales_id: 9994
Unique customers: 793
Unique products: 1862
Date range: 2014-01-03 to 2017-12-30

In [11]:
os.makedirs("../data/processed", exist_ok=True)

fact_sales.to_csv(output_path, index=False)

print(f"fact_sales saved to: {output_path}")

fact_sales saved to: ../data/processed/fact_sales.csv

In [12]:
fact_sales.head(10)

,sales_id,date_id,customer_id,product_id,quantity,sales,discount,profit
0,1,2016-11-08,CG-12520,FUR-BO-10001798,2,261.9600,0.00,41.9136
1,2,2016-11-08,CG-12520,FUR-CH-10000454,3,731.9400,0.00,219.5820
2,3,2016-06-12,DV-13045,OFF-LA-10000240,2,14.6200,0.00,6.8714
3,4,2015-10-11,SO-20335,FUR-TA-10000577,5,957.5775,0.45,-383.0310
4,5,2015-10-11,SO-20335,OFF-ST-10000760,2,22.3680,0.20,2.5164
5,6,2014-06-09,BH-11710,FUR-FU-10001487,7,48.8600,0.00,14.1694
6,7,2014-06-09,BH-11710,OFF-AR-10002833,4,7.2800,0.00,1.9656
7,8,2014-06-09,BH-11710,TEC-PH-10002275,6,907.1520,0.20,90.7152
8,9,2014-06-09,BH-11710,OFF-BI-10003910,3,18.5040,0.20,5.7825
9,10,2014-06-09,BH-11710,OFF-AP-10002892,5,114.9000,0.00,34.4700